apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  ports:
  - port: 3306
  selector:
    app: mysql
  clusterIP: None
---
apiVersion: v1
kind: Service
metadata:
    name: jpatest-service
    labels:
      app: jpatest
spec:
    selector:
        app: jpatest
    ports:
        - port: 8080
          protocol: TCP
          targetPort: 8080
    type: NodePort